### ISSUE TITLE
rendering issue on server

### ISSUE THREAD

**Issue by ghost** [Asek3/Connectedness#4]
#3 hasn't been solved although I updated reforgium to 1.0.12a

**Comment by ghost** [comment]
In addition,sometimes textures are disconnected.It is normal before updating.
![2023-04-25_12 28 48](https://user-images.githubusercontent.com/129179911/234175276-326464ea-1a75-44c2-86ca-669345db99f3.png)

**Comment by Asek3** [comment]
Update Connectedness to 2.0.1a
